# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI Python

on: 
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: ./atendimento/

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - name: Install dependencies (atendimento/)
      run: |
        python -m pip install --upgrade pip
        pip install build
        
    - name: Pytest (atendimento/)
      run: pip install flake8 pytest
      
    - name: Testes (atendimento/)
      run: pytest
      
    - name: Pytest (time/)
      run: pip install flake8 pytest
      
    - name: Testes (time/)
      run: pytest
      
    - name: Pytest (general/)
      run: pip install flake8 pytest
      
    - name: Testes (general/)
      run: pytest
