# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI General

on: 
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: ./general/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - name: Install dependencies (general/)
      run: |
        python -m pip install --upgrade pip
        pip install build
        
    - name: Pytest (general/)
      run: pip install flake8 pytest
      
    - name: Testes (general/)
      run: pytest
      
    - name: Install pytest-html
      run: pip install pytest-html
      
    - name: Generate Test Report
      run: pytest --html=reports.html
      
    - name: Build Package
      run: python generalgame.py sdist bdist_wheel
      
    - name: Build Package
      run: python test_generalgame.py sdist bdist_wheel
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: |
          ./general/reports.html
          ./general/dist/
